name: Generate GitHub Metrics Cards

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. ISO Calendar (Half-Year)
      - name: Generate ISO Calendar Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # 2. Habits
      - name: Generate Habits Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.svg
          base: ""
          plugin_habits: yes

      # 3. Achievements
      - name: Generate Achievements Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes

      # 4. PageSpeed Insights
      - name: Generate PageSpeed Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.pagespeed.svg
          base: ""
          plugin_pagespeedinsights: yes
          plugin_pagespeedinsights_url: https://priyansh.datyal.com
