name: Metrics

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # 1. User Accounts Card
      - name: GitHub User Accounts
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.accounts.svg
          base: ""
          plugin_github_accounts: yes

      # 2. ISO Calendar Card (Half Year)
      - name: ISO Calendar (Half-Year)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.half.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # 3. Habits Card
      - name: GitHub Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.habits.svg
          base: ""
          plugin_habits: yes

      # 4. Achievements Card
      - name: GitHub Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes

      # 5. Calendar Card (Commit History Full Year)
      - name: GitHub Calendar (Full-Year)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.calendar.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_duration: full-year

      # 6. PageSpeed Card
      - name: PageSpeed Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.pagespeed.svg
          base: ""
          plugin_pagespeed: yes
          pagespeed_urls: https://priyansh.datyal.com
